server:
  port: 8080

spring:
  application:
    name: equipment_maintenance
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rbac_menu_db
    username: root
    password: 123456
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.equipment_maintenance.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-actual-param-name: true

sa-token:

  token-name: token

  timeout: 2592000

  active-timeout: -1

  is-concurrent: true

  is-share: true

  token-style: uuid

  is-log: true


