spring:
  application:
    name: device-maintenance
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/lightning
    username: root
    password: 123456

mybatis-plus:
  mapper-locations: classpath*:/mappers/*Mapper.xml
  type-aliases-package: com.example.springboot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    use-actual-param-name: true


server:
  port: 8080